apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: your-dockerhub-username/user-app:IMAGE_TAG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  type: NodePort
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
